name: Build Windows Executable

on:
  push:
    branches:
      - main
      - develop
  # Allows manual triggering from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    # Run only on the latest Windows environment
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install PyInstaller and Dependencies
        run: |
          # Use a stable command to install all required libraries
          python -m pip install --upgrade pip setuptools wheel
          pip install --force-reinstall pyinstaller -r requirements.txt
      
      - name: Build Windows Executable
        run: |
          # PyInstaller command targets cell_analysis_app.py
          # --noconsole for GUI app, --icon for the .ico file
          pyinstaller cell_analysis_app.py --onefile --noconsole --distpath build/windows --name CellAnalyzer --icon icon.ico --collect-all pyqt5 --collect-all cv2 --hidden-import=resources_rc --uac-admin --add-data "icon.ico;."
        shell: bash

      - name: Upload Windows Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CellAnalyzer-Windows-EXE
          # The path points to the single generated EXE inside the build folder
          path: build/windows/CellAnalyzer.exe
          retention-days: 7
