name: Build Windows Executable

on:
  push:
    branches:
      - main
      - develop
  # Allows manual triggering from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install PyInstaller and Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --force-reinstall pyinstaller -r requirements.txt
      
      - name: Build Windows Executable
        run: |
          # PyInstaller command targets cell_analysis_app.py
          pyinstaller cell_analysis_app.py --onefile --noconsole --distpath build/windows --name CellAnalyzer --icon icon.ico --collect-all pyqt5 --collect-all cv2 --hidden-import=resources_rc --uac-admin --add-data "icon.ico;."
        shell: bash

      - name: Upload Windows Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CellAnalyzer-Windows-EXE
          # Path to the actual executable
          path: build/windows/CellAnalyzer.exe
          retention-days: 7

  # --- NEW JOB TO CREATE THE GITHUB RELEASE ---
  create-release:
    # This job runs only AFTER the build-windows job succeeds
    needs: build-windows 
    runs-on: ubuntu-latest
    permissions:
      contents: write # Essential permission to create a release

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: CellAnalyzer-Windows-EXE
          path: release/

      - name: Rename and Prepare File for Release
        # Rename the downloaded artifact to a cleaner name for the release
        run: mv release/CellAnalyzer.exe CellAnalyzer-Windows-x64.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided secret
        with:
          files: CellAnalyzer-Windows-x64.exe
          name: Release ${{ github.ref }} 
          tag_name: v1.0.0-${{ github.run_number }} # Creates a unique tag, e.g., v1.0.0-15
          body: |
            Automated Windows executable release for the Interactive Cell Analyzer app.
            
            Find the standalone .exe file attached below.
